version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: your_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx3edc
      POSTGRES_DB: form_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
